wandb_version: 1

K_epochs:
  desc: null
  value: 40
_wandb:
  desc: null
  value:
    cli_version: 0.12.3
    code_path: code/main.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1633257090
    t:
      1:
      - 1
      - 3
      2:
      - 1
      - 3
      3:
      - 16
      4: 3.9.7
      5: 0.12.3
      8:
      - 3
      - 5
debug_env:
  desc: null
  value: false
env_id:
  desc: null
  value: MyUnityGymEnv-v0
env_path:
  desc: null
  value: drone3D_linux_run61.3c/mse-dreamscape
eps_clip:
  desc: null
  value: 0.2
gamma:
  desc: null
  value: 0.9
has_continuous_action_space:
  desc: null
  value: true
lr_actor:
  desc: null
  value: 0.0003
lr_critic:
  desc: null
  value: 0.001
max_ep_len:
  desc: null
  value: 800
no_graphics:
  desc: null
  value: true
num_env:
  desc: null
  value: 1
test_no_graphics:
  desc: null
  value: true
test_time_scale:
  desc: null
  value: 40
test_total_episodes:
  desc: null
  value: 1
time_scale:
  desc: null
  value: 40
total_timesteps:
  desc: null
  value: 300
worker_id:
  desc: null
  value: 1
