wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.4
    code_path: code/main.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.10
    start_time: 1634493564
    t:
      1:
      - 1
      - 3
      2:
      - 1
      - 3
      3:
      - 16
      - 19
      4: 3.7.10
      5: 0.12.4
      8:
      - 5
batch_size:
  desc: null
  value: 1024
buffer_size:
  desc: null
  value: 10240
clip_range:
  desc: null
  value: 0.2
debug_env:
  desc: null
  value: false
env_id:
  desc: null
  value: MyUnityGymEnv-v0
env_path:
  desc: null
  value: drone3D_linux_run61.3c/mse-dreamscape
export_onnx:
  desc: null
  value: false
gae_lambda:
  desc: null
  value: 0.95
gamma:
  desc: null
  value: 0.99
has_continuous_action_space:
  desc: null
  value: true
log_TFSideStats:
  desc: null
  value: false
lr_actor:
  desc: null
  value: 0.0003
lr_critic:
  desc: null
  value: 0.001
n_epochs:
  desc: null
  value: 3
no_graphics:
  desc: null
  value: true
num_env:
  desc: null
  value: 1
reinitialize_from:
  desc: null
  value: run-20211004_161556-cdp0bn8h
run_dir:
  desc: null
  value: /app/wandb/run-20211017_175924-1259pi7b/files
test_total_episodes:
  desc: null
  value: 0
time_scale:
  desc: null
  value: 50
total_timesteps:
  desc: null
  value: 200
worker_id:
  desc: null
  value: 1
